"""Force add cancelled_quantity and returned_quantity

Revision ID: 96eab8c52e17
Revises: f4a2566a286e
Create Date: 2025-05-11 20:20:19.677571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96eab8c52e17'
down_revision = 'f4a2566a286e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_quantity', sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('returned_quantity', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('returned_quantity')
        batch_op.drop_column('cancelled_quantity')

    # ### end Alembic commands ###
