"""Add coupon_usage and sale_variant

Revision ID: f4a2566a286e
Revises: 79b1377de224
Create Date: 2025-05-08 16:30:28.755663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a2566a286e'
down_revision = '79b1377de224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_variant',
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('sale_id', 'variant_id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('sales_variant_id_fkey', type_='foreignkey')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('sales_variant_id_fkey', 'product_variants', ['variant_id'], ['id'])

    op.drop_table('sale_variant')
    op.drop_table('coupon_usages')
    # ### end Alembic commands ###
